---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: mgmt-telco-shift-zone
 namespace: openshift-gitops
spec:
  generators:
    - git:
        directories:
          - path: clusters/mgmt.telco.shift.zone/config-*
        repoURL: 'https://github.com/openshift-telco/telco-gitops.git'
        revision: HEAD
  template:
    metadata:
      name: 'mgmt-telco-{{path.basename}}'
      namespace: openshift-gitops
    spec:
      destination:
        namespace: openshift-gitops
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: 'https://github.com/openshift-telco/telco-gitops.git'
        targetRevision: HEAD