---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage 
spec:
  managementState: Managed
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: ran.openshift.io/lso
          operator: Exists
  storageClassDevices:
    - storageClassName: "lso-filesystemclass" 
      volumeMode: Filesystem 
      fsType: xfs 
      devicePaths: 
        - /dev/autopart/lv_1 
        - /dev/autopart/lv_2 
        - /dev/autopart/lv_3
    - storageClassName: "lso-blockclass" 
      volumeMode: Block  
      devicePaths: 
        - /dev/autopart/lv_4 
        - /dev/autopart/lv_5