---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/mgmt: telco-gitops

bases:
  #####################################################
  # Operators for MGMT Clusters
  #####################################################
  # Common Telco Optimizations
  - ../../base/configs/telco-optimized
  # OpenShift GitOps
  - ../../base/operators/openshift-gitops
  # OpenShift Pipelines
  - ../../base/operators/openshift-pipelines
  # OpenShift Serverless
  ##- ../../base/operators/openshift-serverless
  # # Assisted Installer (now Infrastructre Operator)
  ##- ../../base/operators/assisted-installer
  # Red Hat Advanced Cluster Manager for Kubernetes
  - ../../base/operators/advanced-cluster-management
  # OpenShift Container storage
  # - ../../base/operators/openshift-container-storage
  # Quay Enterprise
  # - ../../base/operators/quay-enterprise-operator
  # OpenShift Logging
  # - ../../base/operators/openshift-logging
